/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
      extend: {
        colors: {
          "surface-container": "#ebeeef",
          "surface-dim": "#d7dadb",
          "on-tertiary-fixed": "#20005f",
          "on-error": "#ffffff",
          "on-surface-variant": "#3f494a",
          "inverse-surface": "#2d3132",
          "error": "#ba1a1a",
          "secondary-fixed": "#e8ddff",
          "on-tertiary-container": "#ded2ff",
          "on-primary-fixed-variant": "#004f56",
          "surface-container-low": "#f1f4f4",
          "outline-variant": "#bec8ca",
          "tertiary-fixed": "#e8deff",
          "primary-fixed-dim": "#85d3dd",
          "on-secondary": "#ffffff",
          "surface-tint": "#006972",
          "error-container": "#ffdad6",
          "outline": "#6f797a",
          "on-primary": "#ffffff",
          "secondary-container": "#7531ff",
          "on-secondary-container": "#eadfff",
          "tertiary-fixed-dim": "#cdbdff",
          "on-error-container": "#93000a",
          "background": "#f7fafa",
          "primary-container": "#006972",
          "on-surface": "#181c1d",
          "secondary": "#5b00df",
          "tertiary": "#4f00d0",
          "surface-container-lowest": "#ffffff",
          "on-primary-fixed": "#001f23",
          "on-secondary-fixed": "#22005d",
          "surface-bright": "#f7fafa",
          "on-primary-container": "#97e6f0",
          "on-tertiary": "#ffffff",
          "inverse-on-surface": "#eef1f1",
          "on-tertiary-fixed-variant": "#4f00d0",
          "secondary-fixed-dim": "#cfbdff",
          "surface-container-high": "#e6e9e9",
          "surface": "#f7fafa",
          "surface-container-highest": "#e0e3e3",
          "tertiary-container": "#6833ea",
          "inverse-primary": "#85d3dd",
          "primary-fixed": "#a1eff9",
          "on-secondary-fixed-variant": "#5300cd",
          "primary": "#004f56",
          "on-background": "#181c1d",
          "surface-variant": "#e0e3e3"
        },
        fontFamily: {
          "headline": ["Plus Jakarta Sans"],
          "body": ["Plus Jakarta Sans"],
          "label": ["Plus Jakarta Sans"],
          "plus-jakarta": ["Plus Jakarta Sans"],
          "plus-jakarta-sans": ["Plus Jakarta Sans"]
        },
        borderRadius: {"DEFAULT": "0.5rem", "lg": "0.75rem", "xl": "1rem", "full": "9999px"},
      },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries'),
    ],
  }
